data_path: F:/Datasets/lipreading/
char_path: dictionary/zh-cn/cmlr.txt
train: labels/cmlr/cmlr_train.csv  # cmlr_train
val: labels/cmlr/cmlr_val_112.csv
test: labels/cmlr/cmlr_test.csv

data_utils:
  rate_ratio: 640
  max_frames: 1200 #1800
  max_frames_val: 500 #500
  dataset_type: avdataset
  batch_size: 64

